#!/bin/sh
# Keeping options in alphabetical order makes it easy to add more.

while :
do
    case "$1" in
      -h | --help)
	  display_help  # Call your function
	  # no shifting needed here, we're done.
	  exit 0
	  ;;
	-p | --pass)
	  password="$2" # You may want to check validity of $2  s
	  shift 2
	  ;;
      -u | --user)
	  username="$2" # You may want to check validity of $2  s
	  shift 2
	  ;;
      --) # End of all options
	  shift
	  break
	  ;;
      -*)
	  echo "Error: Unknown option: $1" >&2
	  exit 1
	  ;;
      *)  # No more options
	  break
	  ;;
    esac
done
newdir="/mnt/disk/"

if [ -z $password ]
then
echo "password empty"
else
	mkdir -p $newdir$username
	sudo useradd $username
	echo "$username:$password" | sudo chpasswd
	sudo usermod $username -m -d $newdir$username
	sudo chown $username:$username $newdir$username
	sudo usermod -G mail $username
	sudo setquota -u $username 1834784 2096896 0 0 -a /mnt/disk
fi

# End of file
