#!/bin/sh
# Keeping options in alphabetical order makes it easy to add more.

while :
do
    case "$1" in
      -f | --file)
	  file="$2"   # You may want to check validity of $2
	  shift 2
	  ;;
      -h | --help)
	  display_help  # Call your function
	  # no shifting needed here, we're done.
	  exit 0
	  ;;
	-p | --pass)
	  password="$2" # You may want to check validity of $2  s
	  shift 2
	  ;;
      -u | --user)
	  username="$2" # You may want to check validity of $2  s
	  shift 2
	  ;;
      --) # End of all options
	  shift
	  break
	  ;;
      -*)
	  echo "Error: Unknown option: $1" >&2
	  exit 1
	  ;;
      *)  # No more options
	  break
	  ;;
    esac
done
newdir="/var/www/html/"

	mkdir -p $newdir$username
	sudo useradd $username
	echo "$username:$password" | sudo chpasswd

	sudo usermod $username -m -d $newdir$username
	sudo chown $username:$username $newdir$username
	sudo usermod -G mail $username



# End of file
